ActsAsTaggableOn::Tag.create!([
  {name: "waldix"},
  {name: "didier"},
  {name: "prueba"},
  {name: "uno"},
  {name: "arte"},
  {name: "urbano"},
  {name: "video1"},
  {name: "arto"},
  {name: "tigre"},
  {name: "moderno"},
  {name: "graffiti"},
  {name: "fotografia"},
  {name: "festival"},
  {name: "comex"},
  {name: "futbol"},
  {name: "penal"},
  {name: "tiro"},
  {name: "aguila"},
  {name: "artesanal"},
  {name: "cultura"},
  {name: "post1"},
  {name: "paradon"}
])
ActsAsTaggableOn::Tagging.create!([
  {tag_id: 5, taggable_id: 5, taggable_type: "Video", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 6, taggable_id: 5, taggable_type: "Video", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 7, taggable_id: 5, taggable_type: "Video", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 8, taggable_id: 5, taggable_type: "Video", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 9, taggable_id: 6, taggable_type: "Video", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 10, taggable_id: 6, taggable_type: "Video", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 5, taggable_id: 6, taggable_type: "Video", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 11, taggable_id: 7, taggable_type: "Video", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 5, taggable_id: 7, taggable_type: "Video", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 6, taggable_id: 7, taggable_type: "Video", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 8, taggable_id: 7, taggable_type: "Video", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 12, taggable_id: 7, taggable_type: "Photo", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 8, taggable_id: 7, taggable_type: "Photo", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 13, taggable_id: 7, taggable_type: "Photo", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 10, taggable_id: 8, taggable_type: "Photo", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 14, taggable_id: 8, taggable_type: "Photo", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 8, taggable_id: 8, taggable_type: "Photo", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 15, taggable_id: 9, taggable_type: "Photo", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 5, taggable_id: 9, taggable_type: "Photo", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 12, taggable_id: 9, taggable_type: "Photo", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 8, taggable_id: 9, taggable_type: "Photo", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 16, taggable_id: 10, taggable_type: "Photo", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 17, taggable_id: 10, taggable_type: "Photo", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 8, taggable_id: 10, taggable_type: "Photo", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 18, taggable_id: 11, taggable_type: "Photo", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 19, taggable_id: 11, taggable_type: "Photo", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 8, taggable_id: 11, taggable_type: "Photo", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 20, taggable_id: 11, taggable_type: "Photo", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 21, taggable_id: 3, taggable_type: "Post", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 13, taggable_id: 3, taggable_type: "Post", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 8, taggable_id: 3, taggable_type: "Post", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 15, taggable_id: 3, taggable_type: "Post", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 22, taggable_id: 4, taggable_type: "Post", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 8, taggable_id: 4, taggable_type: "Post", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 6, taggable_id: 4, taggable_type: "Post", tagger_id: nil, tagger_type: nil, context: "tags"}
])
User.create!([
  {email: "comex@demo.com", :password => 'comex123', :password_confirmation => 'comex123'}
])
About.create!([
  {name: "¿QUÉ ES COMEX URBANO?", description: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce quis adipiscing nibh, ut tincidunt quam. Praesent ut congue enim. Nulla sed ultrices nunc. Nunc pharetra tristique magna, id tincidunt nisl venenatis at. Aliquam mollis diam vel velit interdum faucibus. Aenean purus nulla, pharetra vel molestie quis, pretium a nulla. Donec non urna et nulla iaculis euismod et id nulla.</p>"},
  {name: "¿DE DÓNDE SURGE COMEX URBANO?", description: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce quis adipiscing nibh, ut tincidunt quam. Praesent ut congue enim. Nulla sed ultrices nunc. Nunc pharetra tristique magna, id tincidunt nisl venenatis at. Aliquam mollis diam vel velit interdum faucibus. Aenean purus nulla, pharetra vel molestie quis, pretium a nulla. Donec non urna et nulla iaculis euismod et id nulla.</p>"}
])
Banner.create!([
  {name: nil, description: nil, active: nil, photo_file_name: "placead1.jpg", photo_content_type: "image/jpeg", photo_file_size: 57825, photo_updated_at: "2014-07-24 21:55:13", landing_page_id: nil},
  {name: nil, description: nil, active: nil, photo_file_name: "placead2.jpg", photo_content_type: "image/jpeg", photo_file_size: 70431, photo_updated_at: "2014-07-24 21:55:15", landing_page_id: nil}
])
Category.create!([
  {name: "Videos", link: "videos", position: 1, active: 1},
  {name: "Galería", link: "photos", position: 2, active: 1},
  {name: "Blog", link: "posts", position: 3, active: 1},
  {name: "¿Qué es urbano?", link: "abouts", position: 4, active: 1}
])
Image.create!([
  {name: "Festival Internacional Comex Urbano", description: "FICU es un festival que da apertura al arte urbano y digital en México.", link: "http://www.google.com", photo_file_name: "featured-image.jpg", photo_content_type: "image/jpeg", photo_file_size: 511217, photo_updated_at: "2014-07-16 23:04:03", landing_page_id: 1},
  {name: "Festival Internacional Comex Urbano", description: "FICU es un festival que da apertura al arte urbano y digital en México.", link: "http://www.google.com", photo_file_name: "featured-image2.jpg", photo_content_type: "image/jpeg", photo_file_size: 358088, photo_updated_at: "2014-07-16 23:04:04", landing_page_id: 1}
])
LandingPage.create!([
  {facebook: "http://www.facebook.com", twitter: "http://www.twitter.com", youtube: "http://www.youtube.com", vimeo: "http://www.vimeo.com", copyright: "Copyright 2014 Consorcio Comex, S.A. de C.V", terms: "Términos y Condiciones / Aviso de Privacidad / Soporte Técnico"}
])
Photo.create!([
  {name: "Festival de Fotografia", description: "<p>hojas &quot;Letraset&quot;, las cuales contenian pasajes de Lorem Ipsum, y m&aacute;s recientemente con software de au</p>\r\n", visit: 1, active: 1, image_file_name: "1.jpg", image_content_type: "image/jpeg", image_file_size: 75347, image_updated_at: "2014-07-24 23:29:30", section_id: 2, posted_at: "2014-07-24"},
  {name: "Festival Moderno de Fotografia", description: "<p>pero la mayor&iacute;a sufri&oacute; alteraciones en alguna manera, ya sea porque se le agreg&oacute; humor, o palabras aleatorias que no parecen ni un poco cre&iacute;bles. Si vas a utilizar un pasaje de Lorem Ipsum, necesit&aacute;s estar seguro de que no hay nada avergonzante escondido en el medio del texto. Todos los generadores de Lorem Ipsum que se encuentran en Internet tienden a repetir trozos predefinidos cuando sea necesario, haciendo a este el &uacute;nico generador verdadero (v&aacute;lido) en la Internet. Usa un diccionario de mas de 200 palabras&nbsp;</p>\r\n", visit: 1, active: 1, image_file_name: "2.jpg", image_content_type: "image/jpeg", image_file_size: 104408, image_updated_at: "2014-07-24 23:31:48", section_id: 2, posted_at: "2011-06-22"},
  {name: "Festival de Cultura", description: "<p>pero la mayor&iacute;a sufri&oacute; alteraciones en alguna manera, ya sea porque se le agreg&oacute; humor, o palabras aleatorias que no parecen ni un poco cre&iacute;bles. Si vas a utilizar un pasaje de Lorem Ipsum, necesit&aacute;s estar seguro de que no hay nada avergonzante escondido en el medio del texto. Todos los generadores de Lorem Ipsum que se encuentran en Internet tienden a repetir trozos predefinidos cuando sea necesario, haciendo a este el &uacute;nico generador verdadero (v&aacute;lido) en la Internet. Usa un diccionario de mas de 200 palabras&nbsp;</p>\r\n", visit: 1, active: 1, image_file_name: "3.jpg", image_content_type: "image/jpeg", image_file_size: 95033, image_updated_at: "2014-07-24 23:32:43", section_id: 2, posted_at: "2009-07-09"},
  {name: "Festival Internacional", description: "<p>pero la mayor&iacute;a sufri&oacute; alteraciones en alguna manera, ya sea porque se le agreg&oacute; humor, o palabras aleatorias que no parecen ni un poco cre&iacute;bles. Si vas a utilizar un pasaje de Lorem Ipsum, necesit&aacute;s estar seguro de que no hay nada avergonzante escondido en el medio del texto. Todos los generadores de Lorem Ipsum que se encuentran en Internet tienden a repetir trozos predefinidos cuando sea necesario, haciendo a este el &uacute;nico generador verdadero (v&aacute;lido) en la Internet. Usa un diccionario de mas de 200 palabras&nbsp;</p>\r\n", visit: 1, active: 1, image_file_name: "4.jpg", image_content_type: "image/jpeg", image_file_size: 47462, image_updated_at: "2014-07-24 23:33:24", section_id: 2, posted_at: "2013-03-21"},
  {name: "Festival Artesanal", description: "<p>pero la mayor&iacute;a sufri&oacute; alteraciones en alguna manera, ya sea porque se le agreg&oacute; humor, o palabras aleatorias que no parecen ni un poco cre&iacute;bles. Si vas a utilizar un pasaje de Lorem Ipsum, necesit&aacute;s estar seguro de que no hay nada avergonzante escondido en el medio del texto. Todos los generadores de Lorem Ipsum que se encuentran en Internet tienden a repetir trozos predefinidos cuando sea necesario, haciendo a este el &uacute;nico generador verdadero (v&aacute;lido) en la Internet. Usa un diccionario de mas de 200 palabras&nbsp;</p>\r\n", visit: 1, active: 1, image_file_name: "Comex_urbano_Galería_Editable.jpg", image_content_type: "image/jpeg", image_file_size: 228869, image_updated_at: "2014-07-24 23:34:41", section_id: 2, posted_at: "2012-05-30"}
])
Post.create!([
  {title: "Festival Internacion Comex Urbano", introduction: "\r\nAl contrario del pensamiento popular, el texto de Lorem Ipsum no es simplemente texto aleatorio. Tiene sus raices en una pieza cl´sica de la literatura del Latin, que data del año 45 antes de Cristo, haciendo que este adquiera mas de 2000 años de antiguedad. Richard McClintock, un profesor de Latin de la Universidad de Hampden-S", description: "<p>Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayor&iacute;a sufri&oacute; alteraciones en alguna manera, ya sea porque se le agreg&oacute; humor, o palabras aleatorias que no parecen ni un poco cre&iacute;bles. Si vas a utilizar un pasaje de Lorem Ipsum, necesit&aacute;s estar seguro de que no hay nada avergonzante escondido en el medio del texto. Todos los generadores de Lorem Ipsum que se encuentran en Internet tienden a repetir trozos predefinidos cuando sea necesario, haciendo a este el &uacute;nico generador verdadero (v&aacute;lido) en la Internet. Usa un diccionario de mas de 200 palabras prove</p>\r\n\r\n<p><img alt=\"\" src=\"http://s3.amazonaws.com/comex_urbano/app/public/ckeditor_assets/pictures/1/content_arte-urbano.jpg\" style=\"height:349px; width:800px\" /></p>\r\n", active: 1, image_file_name: "post1.jpg", image_content_type: "image/jpeg", image_file_size: 23170, image_updated_at: "2014-07-24 23:41:31", section_id: 5, posted_at: "2014-07-07"},
  {title: "Festival de Feria", introduction: "implemente texto aleatorio. Tiene sus raices en una pieza cl´sica de la literatura del Latin, que data del año 45 antes de Cristo, haciendo que este adquiera mas de 2000 años de antiguedad. Richard McClintock, un profesor de Latin de la Universidad de Ham", description: "<p><img alt=\"\" src=\"http://s3.amazonaws.com/comex_urbano/app/public/ckeditor_assets/pictures/2/content_videos-3.jpg\" style=\"height:224px; width:362px\" /></p>\r\n\r\n<p>El trozo de texto est&aacute;ndar de Lorem Ipsum usado desde el a&ntilde;o 1500 es reproducido debajo para aquellos interesados. Las secciones 1.10.32 y 1.10.33 de &quot;de Finibus Bonorum et Malorum&quot; por Cicero son tambi&eacute;n reproducidas en su forma original exacta, acompa&ntilde;adas por versiones en Ingl&eacute;s de la traducci&oacute;n realizada en 1914 por H. Rackham.</p>\r\n", active: 1, image_file_name: "post2.jpg", image_content_type: "image/jpeg", image_file_size: 24251, image_updated_at: "2014-07-24 23:46:40", section_id: 5, posted_at: "2013-07-18"}
])
Publication.create!([
  {content: "<p>Lorem Ipsum&nbsp;es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno est&aacute;ndar de las industrias desde el a&ntilde;o 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido us&oacute; una galer&iacute;a de textos y los mezcl&oacute; de tal manera que logr&oacute; hacer un libro de textos especimen.&nbsp;</p>\r\nFestival Internacional de ArteLorem Ipsum es simplemente el texto de relleno. arte urbano video1 arto", published_id: 5, published_type: "Video"},
  {content: "<p>El punto de usar Lorem Ipsum es que tiene una distribuci&oacute;n m&aacute;s o menos normal de las letras, al contrario de usar textos como por ejemplo &quot;Contenido aqu&iacute;, contenido aqu&iacute;&quot;. Estos textos hacen parecerlo un espa&ntilde;ol que se puede leer. Muchos paquetes de autoedici&oacute;n y editores de p&aacute;ginas web usan el Lore</p>\r\nFestival Internacional de Urbanodesconocido usó una galería de textos y los mezcló tigre moderno arte", published_id: 6, published_type: "Video"},
  {content: "<p>&nbsp;Todos los generadores de Lorem Ipsum que se encuentran en Internet tienden a repetir trozos predefinidos cuando sea necesario, haciendo a este el &uacute;nico generador verdadero (v&aacute;lido) en la Internet. Usa un diccionario de mas de 200 palabras provenie</p>\r\nFestival Internacional de Grafittis variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras graffiti arte urbano arto", published_id: 7, published_type: "Video"},
  {content: "Festival de Fotografia<p>hojas &quot;Letraset&quot;, las cuales contenian pasajes de Lorem Ipsum, y m&aacute;s recientemente con software de au</p>\r\nfotografia arto festival", published_id: 7, published_type: "Photo"},
  {content: "Festival Moderno de Fotografia<p>pero la mayor&iacute;a sufri&oacute; alteraciones en alguna manera, ya sea porque se le agreg&oacute; humor, o palabras aleatorias que no parecen ni un poco cre&iacute;bles. Si vas a utilizar un pasaje de Lorem Ipsum, necesit&aacute;s estar seguro de que no hay nada avergonzante escondido en el medio del texto. Todos los generadores de Lorem Ipsum que se encuentran en Internet tienden a repetir trozos predefinidos cuando sea necesario, haciendo a este el &uacute;nico generador verdadero (v&aacute;lido) en la Internet. Usa un diccionario de mas de 200 palabras&nbsp;</p>\r\nmoderno comex arto", published_id: 8, published_type: "Photo"},
  {content: "Festival de Cultura<p>pero la mayor&iacute;a sufri&oacute; alteraciones en alguna manera, ya sea porque se le agreg&oacute; humor, o palabras aleatorias que no parecen ni un poco cre&iacute;bles. Si vas a utilizar un pasaje de Lorem Ipsum, necesit&aacute;s estar seguro de que no hay nada avergonzante escondido en el medio del texto. Todos los generadores de Lorem Ipsum que se encuentran en Internet tienden a repetir trozos predefinidos cuando sea necesario, haciendo a este el &uacute;nico generador verdadero (v&aacute;lido) en la Internet. Usa un diccionario de mas de 200 palabras&nbsp;</p>\r\nfutbol arte fotografia arto", published_id: 9, published_type: "Photo"},
  {content: "Festival Internacional<p>pero la mayor&iacute;a sufri&oacute; alteraciones en alguna manera, ya sea porque se le agreg&oacute; humor, o palabras aleatorias que no parecen ni un poco cre&iacute;bles. Si vas a utilizar un pasaje de Lorem Ipsum, necesit&aacute;s estar seguro de que no hay nada avergonzante escondido en el medio del texto. Todos los generadores de Lorem Ipsum que se encuentran en Internet tienden a repetir trozos predefinidos cuando sea necesario, haciendo a este el &uacute;nico generador verdadero (v&aacute;lido) en la Internet. Usa un diccionario de mas de 200 palabras&nbsp;</p>\r\npenal tiro arto", published_id: 10, published_type: "Photo"},
  {content: "Festival Artesanal<p>pero la mayor&iacute;a sufri&oacute; alteraciones en alguna manera, ya sea porque se le agreg&oacute; humor, o palabras aleatorias que no parecen ni un poco cre&iacute;bles. Si vas a utilizar un pasaje de Lorem Ipsum, necesit&aacute;s estar seguro de que no hay nada avergonzante escondido en el medio del texto. Todos los generadores de Lorem Ipsum que se encuentran en Internet tienden a repetir trozos predefinidos cuando sea necesario, haciendo a este el &uacute;nico generador verdadero (v&aacute;lido) en la Internet. Usa un diccionario de mas de 200 palabras&nbsp;</p>\r\naguila artesanal arto cultura", published_id: 11, published_type: "Photo"},
  {content: "Festival Internacion Comex Urbano\r\nAl contrario del pensamiento popular, el texto de Lorem Ipsum no es simplemente texto aleatorio. Tiene sus raices en una pieza cl´sica de la literatura del Latin, que data del año 45 antes de Cristo, haciendo que este adquiera mas de 2000 años de antiguedad. Richard McClintock, un profesor de Latin de la Universidad de Hampden-S<p>Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayor&iacute;a sufri&oacute; alteraciones en alguna manera, ya sea porque se le agreg&oacute; humor, o palabras aleatorias que no parecen ni un poco cre&iacute;bles. Si vas a utilizar un pasaje de Lorem Ipsum, necesit&aacute;s estar seguro de que no hay nada avergonzante escondido en el medio del texto. Todos los generadores de Lorem Ipsum que se encuentran en Internet tienden a repetir trozos predefinidos cuando sea necesario, haciendo a este el &uacute;nico generador verdadero (v&aacute;lido) en la Internet. Usa un diccionario de mas de 200 palabras prove</p>\r\n\r\n<p><img alt=\"\" src=\"http://s3.amazonaws.com/comex_urbano/app/public/ckeditor_assets/pictures/1/content_arte-urbano.jpg\" style=\"height:349px; width:800px\" /></p>\r\npost1 festival arto futbol", published_id: 3, published_type: "Post"},
  {content: "Festival de Feriaimplemente texto aleatorio. Tiene sus raices en una pieza cl´sica de la literatura del Latin, que data del año 45 antes de Cristo, haciendo que este adquiera mas de 2000 años de antiguedad. Richard McClintock, un profesor de Latin de la Universidad de Ham<p><img alt=\"\" src=\"http://s3.amazonaws.com/comex_urbano/app/public/ckeditor_assets/pictures/2/content_videos-3.jpg\" style=\"height:224px; width:362px\" /></p>\r\n\r\n<p>El trozo de texto est&aacute;ndar de Lorem Ipsum usado desde el a&ntilde;o 1500 es reproducido debajo para aquellos interesados. Las secciones 1.10.32 y 1.10.33 de &quot;de Finibus Bonorum et Malorum&quot; por Cicero son tambi&eacute;n reproducidas en su forma original exacta, acompa&ntilde;adas por versiones en Ingl&eacute;s de la traducci&oacute;n realizada en 1914 por H. Rackham.</p>\r\nparadon arto urbano", published_id: 4, published_type: "Post"}
])
Role.create!([
  {name: "admin", description: "puedes hacer todo", active: 1}
])
Section.create!([
  {title: "Arte Urbano", description: "<p><img alt=\"\" src=\"http://s3.amazonaws.com/comex_urbano/Users/Waldix/Documents/arto/comex_urbano/public/ckeditor_assets/pictures/1/content_arte-urbano.jpg\" style=\"height:376px; width:895px\" /></p>\r\n\r\n<p>Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno est&aacute;ndar de las industrias desde el a&ntilde;o 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido us&oacute; una galer&iacute;a de textos y los mezcl&oacute; de tal manera que logr&oacute; hacer un libro de textos especimen. No s&oacute;lo sobrevivi&oacute; 500 a&ntilde;os, sino que tambien ingres&oacute; como texto de relleno en documentos electr&oacute;nicos, quedando esencialmente igual al original. Fue popularizado en los 60s con la creaci&oacute;n de las hojas &quot;Letraset&quot;, las cuales contenian pasajes de Lorem Ipsum, y m&aacute;s recientemente con software de autoedici&oacute;n, como por ejemplo Aldus PageMaker, el cual incluye versiones de Lorem Ipsum.</p>\r\n", category_id: 1, active: 1, main_banner_file_name: "banner_principal.png", main_banner_content_type: "image/png", main_banner_file_size: 650965, main_banner_updated_at: "2014-06-19 00:54:34", secondary_banner_file_name: "banner_secundario.png", secondary_banner_content_type: "image/png", secondary_banner_file_size: 563369, secondary_banner_updated_at: "2014-06-19 00:54:36"},
  {title: "Arte Moderno", description: "<p>hola</p>\r\n", category_id: 2, active: 1, main_banner_file_name: "Comex_urbano_Galería_Editable.jpg", main_banner_content_type: "image/jpeg", main_banner_file_size: 228869, main_banner_updated_at: "2014-07-17 06:18:29", secondary_banner_file_name: nil, secondary_banner_content_type: nil, secondary_banner_file_size: nil, secondary_banner_updated_at: nil},
  {title: "Arte Contemporaneo", description: "<p>sfsfsff</p>\r\n", category_id: 2, active: 1, main_banner_file_name: "Comex_urbano_Galería_Editable.jpg", main_banner_content_type: "image/jpeg", main_banner_file_size: 228869, main_banner_updated_at: "2014-07-17 09:04:41", secondary_banner_file_name: nil, secondary_banner_content_type: nil, secondary_banner_file_size: nil, secondary_banner_updated_at: nil},
  {title: "Arte Moderno", description: "<p><img alt=\"\" src=\"http://s3.amazonaws.com/comex_urbano/Users/Waldix/Documents/arto/comex_urbano/public/ckeditor_assets/pictures/2/content_post3.jpg\" style=\"height:231px; width:304px\" /></p>\r\n\r\n<p>Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno est&aacute;ndar de las industrias desde el a&ntilde;o 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido us&oacute; una galer&iacute;a de textos y los mezcl&oacute; de tal manera que logr&oacute; hacer un libro de textos especimen. No s&oacute;lo sobrevivi&oacute; 500 a&ntilde;os, sino que tambien ingres&oacute; como texto de relleno en documentos electr&oacute;nicos, quedando esencialmente igual al original. Fue popularizado en los 60s con la creaci&oacute;n de las hojas &quot;Letraset&quot;, las cuales contenian pasajes de Lorem Ipsum, y m&aacute;s recientemente con software de autoedici&oacute;n, como por ejemplo Aldus PageMaker, el cual incluye versiones de Lorem Ipsum.</p>\r\n", category_id: 1, active: 1, main_banner_file_name: "featured-image2.jpg", main_banner_content_type: "image/jpeg", main_banner_file_size: 358088, main_banner_updated_at: "2014-07-17 09:42:39", secondary_banner_file_name: nil, secondary_banner_content_type: nil, secondary_banner_file_size: nil, secondary_banner_updated_at: nil},
  {title: "Arte Realista", description: "<p>Lorem Ipsum&nbsp;es simplemente el texto de relleno de las imprentas y archivos de texto.</p>\r\n", category_id: 3, active: 1, main_banner_file_name: "blog-section.jpg", main_banner_content_type: "image/jpeg", main_banner_file_size: 76119, main_banner_updated_at: "2014-07-24 21:56:32", secondary_banner_file_name: nil, secondary_banner_content_type: nil, secondary_banner_file_size: nil, secondary_banner_updated_at: nil}
])
Video.create!([
  {name: "Festival Internacional de Arte", description: "Lorem Ipsum es simplemente el texto de relleno. ", content: "<p>Lorem Ipsum&nbsp;es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno est&aacute;ndar de las industrias desde el a&ntilde;o 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido us&oacute; una galer&iacute;a de textos y los mezcl&oacute; de tal manera que logr&oacute; hacer un libro de textos especimen.&nbsp;</p>\r\n", link: "https://www.youtube.com/watch?v=9tZpmHPl2hk", visit: nil, active: 1, section_id: 1, posted_at: "2014-07-24"},
  {name: "Festival Internacional de Urbano", description: "desconocido usó una galería de textos y los mezcló ", content: "<p>El punto de usar Lorem Ipsum es que tiene una distribuci&oacute;n m&aacute;s o menos normal de las letras, al contrario de usar textos como por ejemplo &quot;Contenido aqu&iacute;, contenido aqu&iacute;&quot;. Estos textos hacen parecerlo un espa&ntilde;ol que se puede leer. Muchos paquetes de autoedici&oacute;n y editores de p&aacute;ginas web usan el Lore</p>\r\n", link: "https://www.youtube.com/watch?v=PXQrUpB0Jq8", visit: nil, active: 1, section_id: 4, posted_at: "2013-02-13"},
  {name: "Festival Internacional de Grafitti", description: "s variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras ", content: "<p>&nbsp;Todos los generadores de Lorem Ipsum que se encuentran en Internet tienden a repetir trozos predefinidos cuando sea necesario, haciendo a este el &uacute;nico generador verdadero (v&aacute;lido) en la Internet. Usa un diccionario de mas de 200 palabras provenie</p>\r\n", link: "https://www.youtube.com/watch?v=3LxBb2jxRWU", visit: nil, active: 1, section_id: 1, posted_at: "2012-10-18"}
])