ActsAsTaggableOn::Tag.create!([
  {name: "arto"},
  {name: "video"},
  {name: "urbano"},
  {name: "video2"},
  {name: "graffiti"},
  {name: "video3"},
  {name: "tigre"},
  {name: "imagen1"},
  {name: "patada"},
  {name: "imagen2"},
  {name: "futbol"},
  {name: "verde"},
  {name: "imagen4"},
  {name: "blog1"},
  {name: "blog3"}
])
ActsAsTaggableOn::Tagging.create!([
  {tag_id: 1, taggable_id: 1, taggable_type: "Video", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 2, taggable_id: 1, taggable_type: "Video", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 3, taggable_id: 1, taggable_type: "Video", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 4, taggable_id: 2, taggable_type: "Video", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 1, taggable_id: 2, taggable_type: "Video", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 5, taggable_id: 2, taggable_type: "Video", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 1, taggable_id: 3, taggable_type: "Video", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 4, taggable_id: 3, taggable_type: "Video", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 1, taggable_id: 4, taggable_type: "Video", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 6, taggable_id: 4, taggable_type: "Video", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 7, taggable_id: 4, taggable_type: "Video", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 1, taggable_id: 1, taggable_type: "Photo", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 8, taggable_id: 1, taggable_type: "Photo", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 9, taggable_id: 1, taggable_type: "Photo", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 1, taggable_id: 2, taggable_type: "Photo", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 10, taggable_id: 2, taggable_type: "Photo", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 11, taggable_id: 2, taggable_type: "Photo", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 1, taggable_id: 3, taggable_type: "Photo", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 12, taggable_id: 3, taggable_type: "Photo", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 1, taggable_id: 4, taggable_type: "Photo", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 13, taggable_id: 4, taggable_type: "Photo", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 1, taggable_id: 5, taggable_type: "Photo", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 3, taggable_id: 5, taggable_type: "Photo", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 1, taggable_id: 1, taggable_type: "Post", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 14, taggable_id: 1, taggable_type: "Post", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 1, taggable_id: 2, taggable_type: "Post", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 15, taggable_id: 2, taggable_type: "Post", tagger_id: nil, tagger_type: nil, context: "tags"}
])
Impression.create!([
  {impressionable_type: "Post", impressionable_id: 1, user_id: 1, controller_name: "posts", action_name: "show", view_name: nil, request_hash: "4cb110c10203c691c6d0f35088aa97cad58565b5dc060268c0be5704feff1e25", ip_address: "127.0.0.1", session_hash: "bce6969ec9b2356e5362fbf7e3be924a", message: nil, referrer: "http://localhost:3000/posts"},
  {impressionable_type: "Photo", impressionable_id: 1, user_id: 1, controller_name: "photos", action_name: "show", view_name: nil, request_hash: "4d27aecef16ee77ecfb31591ad77ae9d38eaf3eaf9318e061d6392fcbddd35ab", ip_address: "127.0.0.1", session_hash: "bce6969ec9b2356e5362fbf7e3be924a", message: nil, referrer: "http://localhost:3000/photos"},
  {impressionable_type: "Post", impressionable_id: 2, user_id: 1, controller_name: "posts", action_name: "show", view_name: nil, request_hash: "cf1c7b7677665946392896471a6696be5f3c00a1386d769614bcd8da0787aff9", ip_address: "127.0.0.1", session_hash: "bce6969ec9b2356e5362fbf7e3be924a", message: nil, referrer: "http://localhost:3000/posts"},
  {impressionable_type: "Video", impressionable_id: 1, user_id: 1, controller_name: "videos", action_name: "show", view_name: nil, request_hash: "e4b4a3c527273eb36da1f3a616951628e557fa6e70c73b155cb28eef85826298", ip_address: "127.0.0.1", session_hash: "c2892378a639fcbc8563ab75ddfafae0", message: nil, referrer: "http://localhost:3000/videos"},
  {impressionable_type: "Photo", impressionable_id: 1, user_id: 1, controller_name: "photos", action_name: "show", view_name: nil, request_hash: "9d5a17d1caa0341f540516a17dfc195abce9ac03d2e280a5b558762fdfee85b7", ip_address: "127.0.0.1", session_hash: "c2892378a639fcbc8563ab75ddfafae0", message: nil, referrer: "http://localhost:3000/photos"},
  {impressionable_type: "Post", impressionable_id: 1, user_id: 1, controller_name: "posts", action_name: "show", view_name: nil, request_hash: "798aba8da44592c16f0b77b94a480d65d2bfde31668a4c5e5267e8f1269a47fe", ip_address: "127.0.0.1", session_hash: "c2892378a639fcbc8563ab75ddfafae0", message: nil, referrer: "http://localhost:3000/posts"},
  {impressionable_type: "Photo", impressionable_id: 4, user_id: 1, controller_name: "photos", action_name: "show", view_name: nil, request_hash: "e6086aa877a67a694e14e09d5ce71b934b58fbddc4cccbba7011e0c620adc4dd", ip_address: "127.0.0.1", session_hash: "c2892378a639fcbc8563ab75ddfafae0", message: nil, referrer: "http://localhost:3000/photos"}
])
User.create!([
  {email: "oswaldo@comex.com", encrypted_password: "$2a$10$StGK/wSXXPb3w7wWqMKVGeKVcA.ORjp2Yix7o4utGVZfvvXJeXZNm", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2014-07-30 00:32:19", last_sign_in_at: "2014-07-30 00:32:19", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1"},
  {email: "waldix@comex.com", encrypted_password: "$2a$10$zIUJmRzVheT50SV42LAA/eHWM43uafsEhqDLr6S/gOWTjjYuK75W6", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 5, current_sign_in_at: "2014-08-01 00:52:37", last_sign_in_at: "2014-07-30 00:37:37", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1"},
  {email: "custodidier@comex.com", encrypted_password: "$2a$10$bPnU06GBi4OMl5jtgBHVWe67I5vZ4O6MoW7iglWPr.G5cnyKvJ2mG", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2014-08-01 06:38:46", last_sign_in_at: "2014-08-01 06:38:46", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1"},
  {email: "comex@demo.com", encrypted_password: "$2a$10$d9sjXS0uOSHRDjpuu/MBvu8QABK/19hlpZ1ivhIEvA5MQBjuLJ6w6", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 8, current_sign_in_at: "2014-08-01 08:07:22", last_sign_in_at: "2014-08-01 00:41:53", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1"}
])
About.create!([
  {name: "¿QUÉ ES COMEX URBANO?", description: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce quis adipiscing nibh, ut tincidunt quam. Praesent ut congue enim. Nulla sed ultrices nunc. Nunc pharetra tristique magna, id tincidunt nisl venenatis at. Aliquam mollis diam vel velit interdum faucibus. Aenean purus nulla, pharetra vel molestie quis, pretium a nulla. Donec non urna et nulla iaculis euismod et id nulla.</p>"},
  {name: "¿DE DÓNDE SURGE COMEX URBANO?", description: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce quis adipiscing nibh, ut tincidunt quam. Praesent ut congue enim. Nulla sed ultrices nunc. Nunc pharetra tristique magna, id tincidunt nisl venenatis at. Aliquam mollis diam vel velit interdum faucibus. Aenean purus nulla, pharetra vel molestie quis, pretium a nulla. Donec non urna et nulla iaculis euismod et id nulla.</p>"}
])
Banner.create!([
  {name: nil, description: nil, active: nil, photo_file_name: "placead1.jpg", photo_content_type: "image/jpeg", photo_file_size: 57825, photo_updated_at: "2014-07-29 04:18:15", landing_page_id: nil},
  {name: nil, description: nil, active: nil, photo_file_name: "placead2.jpg", photo_content_type: "image/jpeg", photo_file_size: 70431, photo_updated_at: "2014-07-29 04:18:21", landing_page_id: nil},
  {name: nil, description: nil, active: nil, photo_file_name: "placead2.jpg", photo_content_type: "image/jpeg", photo_file_size: 70431, photo_updated_at: "2014-07-29 04:18:24", landing_page_id: nil},
  {name: nil, description: nil, active: nil, photo_file_name: "placead1.jpg", photo_content_type: "image/jpeg", photo_file_size: 57825, photo_updated_at: "2014-07-29 04:18:26", landing_page_id: nil}
])
Category.create!([
  {name: "Videos", link: "videos", position: 1, active: 1},
  {name: "Galería", link: "photos", position: 2, active: 1},
  {name: "Blog", link: "posts", position: 3, active: 1},
  {name: "¿Qué es urbano?", link: "abouts", position: 4, active: 1}
])
Image.create!([
  {name: "Festival Internacional de Arte Urbano", description: "Festival Internacional de Arte Urbano Festival Internacional de Arte Urbano", link: "http://www.codetlan.com", photo_file_name: "featured-image.jpg", photo_content_type: "image/jpeg", photo_file_size: 511217, photo_updated_at: "2014-07-29 03:44:53", landing_page_id: 1},
  {name: "Festival Internacional de Arte Barroco", description: "Festival Internacional de Arte Barroco Festival Internacional de Arte Barroco", link: "http://www.google.com", photo_file_name: "featured-image2.jpg", photo_content_type: "image/jpeg", photo_file_size: 358088, photo_updated_at: "2014-07-30 05:18:21", landing_page_id: 1}
])
LandingPage.create!([
  {facebook: "http://www.facebook.com", twitter: "http://www.twitter.com", youtube: "http://www.youtube.com", vimeo: "http://www.vimeo.com", copyright: "Copyright 2014 Consorcio Comex, S.A. de C.V", terms: "Términos y Condiciones / Aviso de Privacidad / Soporte Técnico"}
])
Photo.create!([
  {name: "Imagen 1 Arte", description: "<p>Latin de la Universidad de Hampden-Sydney en Virginia, encontr&oacute; una de las palabras m&aacute;s oscuras de la lengua del lat&iacute;n, &quot;consecteur&quot;, en un pasaje de Lorem Ipsum, y al seguir leyendo distintos textos del lat&iacute;n, descubri&oacute; la fuente indudable. Lorem Ipsum viene de las secciones 1.10.32 y 1.10.33 de &quot;de Finnibus Bonorum et Malorum&quot; (Los Extremos del Bien y El Mal) por Cicero, escrito en el a&ntilde;o 45 antes de Cristo. Este libro es un tratado de teor&iacute;a de &eacute;ticas, mu</p>\r\n", visit: nil, active: 1, image_file_name: "2.jpg", image_content_type: "image/jpeg", image_file_size: 104408, image_updated_at: "2014-07-29 03:52:58", section_id: 2, posted_at: "2014-07-23"},
  {name: "Imagen 2 Arte", description: "<p>sufri&oacute; alteraciones en alguna manera, ya sea porque se le agreg&oacute; humor, o palabras aleatorias que no parecen ni un poco cre&iacute;bles. Si vas a utilizar un pasaje de Lorem Ipsum, necesit&aacute;s estar seguro de que no hay nada avergonzante escondido en el medio del texto. Todos los generadores de Lorem Ipsum que se encuentran en Internet tienden a repetir trozos predefinidos cuando se</p>\r\n", visit: nil, active: 1, image_file_name: "3.jpg", image_content_type: "image/jpeg", image_file_size: 95033, image_updated_at: "2014-07-29 03:54:13", section_id: 2, posted_at: "2011-01-12"},
  {name: "Imagen verde", description: "<p>ra mas de 2000 a&ntilde;os de antiguedad. Richard McClintock, un profesor de Latin de la Universidad de Hampden-Sydney en Virginia, encontr&oacute; una de las palabras m&aacute;s oscuras de la lengua del lat&iacute;n, &quot;consecteur&quot;, en un pasaje de Lorem Ipsum, y al seguir leyendo distintos textos del lat&iacute;n, descubri&oacute; la fuente indudable. Lorem Ipsum viene de las secciones 1.10.32 y 1.10.33 de &quot;de Finnibus Bonorum et Malorum&quot; (Los Extremos del Bien y El Mal) por Cicero, es</p>\r\n", visit: nil, active: 1, image_file_name: "color_2.jpg", image_content_type: "image/jpeg", image_file_size: 14683, image_updated_at: "2014-07-29 03:55:14", section_id: 2, posted_at: "2011-09-08"},
  {name: "Imagen 3 Arte", description: "<p>El trozo de texto est&aacute;ndar de Lorem Ipsum usado desde el a&ntilde;o 1500 es reproducido debajo para aquellos interesados. Las secciones 1.10.32 y 1.10.33 de &quot;de Finibus Bonorum et Malorum&quot; por Cicero son tambi&eacute;n reproducidas en su forma original exacta, acompa&ntilde;adas por versiones en Ingl&eacute;s de la traducci&oacute;n realizada en 1914 por H. Rackham.</p>\r\n", visit: nil, active: 1, image_file_name: "Comex_urbano_Galería_Editable.jpg", image_content_type: "image/jpeg", image_file_size: 228869, image_updated_at: "2014-07-29 03:56:06", section_id: 2, posted_at: "2014-07-10"},
  {name: "Imagen 4 Arte", description: "<p>ontenido del texto de un sitio mientras que mira su dise&ntilde;o. El punto de usar Lorem Ipsum es que tiene una distribuci&oacute;n m&aacute;s o menos normal de las letras, al contrario de usar textos como por ejemplo &quot;Contenido aqu&iacute;, contenido aqu&iacute;&quot;. Estos textos hacen parecerlo un espa&ntilde;ol que se puede leer. Muchos paquetes de autoedici&oacute;n y editores de p&aacute;ginas web usan el Lorem Ipsum como su texto por defecto, y al hacer una b&uacute;squeda de &quot;Lorem Ipsum&quot; va a dar por resultado muchos sitios web que usan este te</p>\r\n", visit: nil, active: 1, image_file_name: "4.jpg", image_content_type: "image/jpeg", image_file_size: 47462, image_updated_at: "2014-07-29 03:57:17", section_id: 2, posted_at: "2011-07-20"}
])
Post.create!([
  {title: "Blog 1 ", introduction: "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. Si vas a utilizar un pasaje de Lorem Ipsum, nece", description: "<p>Al contrario del pensamiento popular, el texto de Lorem Ipsum no es simplemente texto aleatorio. Tiene sus raices en una pieza cl&acute;sica de la literatura del Latin, que data del a&ntilde;o 45 antes de Cristo, haciendo que este adquiera mas de 2000 a&ntilde;os de antiguedad. Richard McClintock, un profesor de Latin de la Universidad de Hampden-Sydney en Virginia, encontr&oacute; una de las palabras m&aacute;s oscuras de la lengua del lat&iacute;n, &quot;consecteur&quot;, en un pasaje de Lorem Ipsum, y al seguir leyendo distintos textos del lat&iacute;n, descubri&oacute; la fuente indudable. Lorem Ipsum viene de las secciones 1.10.32 y 1.10.33 de &quot;de Finnibus Bonorum et Malorum&quot; (Los Extremos del Bien y El Mal) por Cicero, escrito en el a&ntilde;o 45 antes de Cristo. Este libro es un tratado de teor&iacute;a de &eacute;ticas, muy popular durante el Renacimiento. La primera linea del Lorem Ipsum, &quot;Lorem ipsum dolor sit amet..&quot;, viene de una linea en la secci&oacute;n 1.10.32</p>\r\n", active: 1, image_file_name: "post1.jpg", image_content_type: "image/jpeg", image_file_size: 23170, image_updated_at: "2014-07-29 03:58:52", section_id: 3, posted_at: "2014-07-25"},
  {title: "Blog 2", introduction: "je de Lorem Ipsum, y al seguir leyendo distintos textos del latín, descubrió la fuente indudable. Lorem Ipsum viene de las secciones 1.10.32 y 1.10.33 de \"de Finnibus Bonorum et Malorum\" (Los Extremos del Bien y El Mal) por Cicero, esc", description: "<p>El trozo de texto est&aacute;ndar de Lorem Ipsum usado desde el a&ntilde;o 1500 es reproducido debajo para aquellos interesados. Las secciones 1.10.32 y 1.10.33 de &quot;de Finibus Bonorum et Malorum&quot; por Cicero son tambi&eacute;n reproducidas en su forma original exacta, acompa&ntilde;adas por versiones en Ingl&eacute;s de la traducci&oacute;n realizada en 1914 por H. Rackham.</p>\r\n", active: 1, image_file_name: "post3.jpg", image_content_type: "image/jpeg", image_file_size: 22161, image_updated_at: "2014-07-29 04:01:32", section_id: 3, posted_at: "2013-07-20"}
])
Publication.create!([
  {content: "<p>No s&oacute;lo sobrevivi&oacute; 500 a&ntilde;os, sino que tambien ingres&oacute; como texto de relleno en documentos electr&oacute;nicos, quedando esencialmente igual al original. Fue popularizado en los 60s con la creaci&oacute;n de las hojas &quot;Letraset&quot;, las cuales contenian pasajes de Lorem Ipsum, y m&aacute;s recientemente con software de autoedici&oacute;n, como&nbsp;</p>\r\nVideo de Arte Urbanotexto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias arto video urbano", published_id: 1, published_type: "Video"},
  {content: "<p>de las letras, al contrario de usar textos como por ejemplo &quot;Contenido aqu&iacute;, contenido aqu&iacute;&quot;. Estos textos hacen parecerlo un espa&ntilde;ol que se puede leer. Muchos paquetes de autoedici&oacute;n y editores de p&aacute;ginas web usan el Lorem Ipsum</p>\r\nVideo de Arte Urbano GrafittiEl punto de usar Lorem Ipsum es que tiene una distribución más o menos normal de las letrasvideo2 arto graffiti", published_id: 2, published_type: "Video"},
  {content: "<p>&nbsp;puede leer. Muchos paquetes de autoedici&oacute;n y editores de p&aacute;ginas web usan el Lorem Ipsum como su texto por defecto, y al hacer una b&uacute;squeda de &quot;Lorem Ipsum&quot; va a dar por resultado muchos sitios web que usan este texto si se encuentran en estado de desarrollo. Muchas versiones han evolucion</p>\r\nVideo de Arte Modernocontenido del texto de un sitio mientras que mira su diseño. El punto de usar Lorem Ipsum es que tiene arto video2", published_id: 3, published_type: "Video"},
  {content: "<p>Si vas a utilizar un pasaje de Lorem Ipsum, necesit&aacute;s estar seguro de que no hay nada avergonzante escondido en el medio del texto. Todos los generadores de Lorem Ipsum que se encuentran en Internet tienden a repetir trozos predefinidos cuando sea necesario, haciendo a este el &uacute;nico generador verdadero (v&aacute;li</p>\r\nVIdeo de Arte TigreHay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguarto video3 tigre", published_id: 4, published_type: "Video"},
  {content: "Imagen 1 Arte<p>Latin de la Universidad de Hampden-Sydney en Virginia, encontr&oacute; una de las palabras m&aacute;s oscuras de la lengua del lat&iacute;n, &quot;consecteur&quot;, en un pasaje de Lorem Ipsum, y al seguir leyendo distintos textos del lat&iacute;n, descubri&oacute; la fuente indudable. Lorem Ipsum viene de las secciones 1.10.32 y 1.10.33 de &quot;de Finnibus Bonorum et Malorum&quot; (Los Extremos del Bien y El Mal) por Cicero, escrito en el a&ntilde;o 45 antes de Cristo. Este libro es un tratado de teor&iacute;a de &eacute;ticas, mu</p>\r\narto imagen1 patada", published_id: 1, published_type: "Photo"},
  {content: "Imagen 2 Arte<p>sufri&oacute; alteraciones en alguna manera, ya sea porque se le agreg&oacute; humor, o palabras aleatorias que no parecen ni un poco cre&iacute;bles. Si vas a utilizar un pasaje de Lorem Ipsum, necesit&aacute;s estar seguro de que no hay nada avergonzante escondido en el medio del texto. Todos los generadores de Lorem Ipsum que se encuentran en Internet tienden a repetir trozos predefinidos cuando se</p>\r\narto imagen2 futbol", published_id: 2, published_type: "Photo"},
  {content: "Imagen verde<p>ra mas de 2000 a&ntilde;os de antiguedad. Richard McClintock, un profesor de Latin de la Universidad de Hampden-Sydney en Virginia, encontr&oacute; una de las palabras m&aacute;s oscuras de la lengua del lat&iacute;n, &quot;consecteur&quot;, en un pasaje de Lorem Ipsum, y al seguir leyendo distintos textos del lat&iacute;n, descubri&oacute; la fuente indudable. Lorem Ipsum viene de las secciones 1.10.32 y 1.10.33 de &quot;de Finnibus Bonorum et Malorum&quot; (Los Extremos del Bien y El Mal) por Cicero, es</p>\r\narto verde", published_id: 3, published_type: "Photo"},
  {content: "Imagen 3 Arte<p>El trozo de texto est&aacute;ndar de Lorem Ipsum usado desde el a&ntilde;o 1500 es reproducido debajo para aquellos interesados. Las secciones 1.10.32 y 1.10.33 de &quot;de Finibus Bonorum et Malorum&quot; por Cicero son tambi&eacute;n reproducidas en su forma original exacta, acompa&ntilde;adas por versiones en Ingl&eacute;s de la traducci&oacute;n realizada en 1914 por H. Rackham.</p>\r\narto imagen4", published_id: 4, published_type: "Photo"},
  {content: "Imagen 4 Arte<p>ontenido del texto de un sitio mientras que mira su dise&ntilde;o. El punto de usar Lorem Ipsum es que tiene una distribuci&oacute;n m&aacute;s o menos normal de las letras, al contrario de usar textos como por ejemplo &quot;Contenido aqu&iacute;, contenido aqu&iacute;&quot;. Estos textos hacen parecerlo un espa&ntilde;ol que se puede leer. Muchos paquetes de autoedici&oacute;n y editores de p&aacute;ginas web usan el Lorem Ipsum como su texto por defecto, y al hacer una b&uacute;squeda de &quot;Lorem Ipsum&quot; va a dar por resultado muchos sitios web que usan este te</p>\r\narto urbano", published_id: 5, published_type: "Photo"},
  {content: "Blog 1 Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. Si vas a utilizar un pasaje de Lorem Ipsum, nece<p>Al contrario del pensamiento popular, el texto de Lorem Ipsum no es simplemente texto aleatorio. Tiene sus raices en una pieza cl&acute;sica de la literatura del Latin, que data del a&ntilde;o 45 antes de Cristo, haciendo que este adquiera mas de 2000 a&ntilde;os de antiguedad. Richard McClintock, un profesor de Latin de la Universidad de Hampden-Sydney en Virginia, encontr&oacute; una de las palabras m&aacute;s oscuras de la lengua del lat&iacute;n, &quot;consecteur&quot;, en un pasaje de Lorem Ipsum, y al seguir leyendo distintos textos del lat&iacute;n, descubri&oacute; la fuente indudable. Lorem Ipsum viene de las secciones 1.10.32 y 1.10.33 de &quot;de Finnibus Bonorum et Malorum&quot; (Los Extremos del Bien y El Mal) por Cicero, escrito en el a&ntilde;o 45 antes de Cristo. Este libro es un tratado de teor&iacute;a de &eacute;ticas, muy popular durante el Renacimiento. La primera linea del Lorem Ipsum, &quot;Lorem ipsum dolor sit amet..&quot;, viene de una linea en la secci&oacute;n 1.10.32</p>\r\narto blog1", published_id: 1, published_type: "Post"},
  {content: "Blog 2je de Lorem Ipsum, y al seguir leyendo distintos textos del latín, descubrió la fuente indudable. Lorem Ipsum viene de las secciones 1.10.32 y 1.10.33 de \"de Finnibus Bonorum et Malorum\" (Los Extremos del Bien y El Mal) por Cicero, esc<p>El trozo de texto est&aacute;ndar de Lorem Ipsum usado desde el a&ntilde;o 1500 es reproducido debajo para aquellos interesados. Las secciones 1.10.32 y 1.10.33 de &quot;de Finibus Bonorum et Malorum&quot; por Cicero son tambi&eacute;n reproducidas en su forma original exacta, acompa&ntilde;adas por versiones en Ingl&eacute;s de la traducci&oacute;n realizada en 1914 por H. Rackham.</p>\r\narto blog3", published_id: 2, published_type: "Post"}
])
Role.create!([
  {name: "Admin", description: "Puedes editar toda el administrador.", active: 1},
  {name: "Blog", description: "Solo puede editar el blog.", active: 1},
  {name: "Galeria", description: "Puedes agregar, editar o eliminar la galeria.", active: 1},
  {name: "Videos", description: "Se puede agregar, editar o eliminar un videos.", active: 1},
  {name: "Menu", description: "Podras modificar los nombres y links del menu principal.", active: 1}
])
Section.create!([
  {title: "Arte Urbano", description: "<p><img alt=\"\" src=\"http://s3.amazonaws.com/comex_urbano/Users/Waldix/Documents/arto/comex_urbano/public/ckeditor_assets/pictures/1/content_arte-urbano.jpg\" style=\"height:376px; width:895px\" /></p>\r\n\r\n<p>Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno est&aacute;ndar de las industrias desde el a&ntilde;o 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido us&oacute; una galer&iacute;a de textos y los mezcl&oacute; de tal manera que logr&oacute; hacer un libro de textos especimen. No s&oacute;lo sobrevivi&oacute; 500 a&ntilde;os, sino que tambien ingres&oacute; como texto de relleno en documentos electr&oacute;nicos, quedando esencialmente igual al original. Fue popularizado en los 60s con la creaci&oacute;n de las hojas &quot;Letraset&quot;, las cuales contenian pasajes de Lorem Ipsum, y m&aacute;s recientemente con software de autoedici&oacute;n, como por ejemplo Aldus PageMaker, el cual incluye versiones de Lorem Ipsum.</p>\r\n", category_id: 1, active: 1, main_banner_file_name: "videos-section.jpg", main_banner_content_type: "image/jpeg", main_banner_file_size: 213749, main_banner_updated_at: "2014-07-26 07:08:15", secondary_banner_file_name: nil, secondary_banner_content_type: nil, secondary_banner_file_size: nil, secondary_banner_updated_at: nil},
  {title: "Arte Moderno", description: "<p>n,mnnnm</p>\r\n", category_id: 2, active: 1, main_banner_file_name: "Comex_urbano_Galería_Editable.jpg", main_banner_content_type: "image/jpeg", main_banner_file_size: 228869, main_banner_updated_at: "2014-07-26 07:22:36", secondary_banner_file_name: nil, secondary_banner_content_type: nil, secondary_banner_file_size: nil, secondary_banner_updated_at: nil},
  {title: "Arte Realista", description: "<p>Lorem Ipsum&nbsp;es simplemente el texto de relleno de las imprentas y archivos de texto.</p>\r\n", category_id: 3, active: 1, main_banner_file_name: "blog-section.jpg", main_banner_content_type: "image/jpeg", main_banner_file_size: 76119, main_banner_updated_at: "2014-07-26 07:30:55", secondary_banner_file_name: nil, secondary_banner_content_type: nil, secondary_banner_file_size: nil, secondary_banner_updated_at: nil}
])
Video.create!([
  {name: "Video de Arte Urbano", description: "texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias ", content: "<p>No s&oacute;lo sobrevivi&oacute; 500 a&ntilde;os, sino que tambien ingres&oacute; como texto de relleno en documentos electr&oacute;nicos, quedando esencialmente igual al original. Fue popularizado en los 60s con la creaci&oacute;n de las hojas &quot;Letraset&quot;, las cuales contenian pasajes de Lorem Ipsum, y m&aacute;s recientemente con software de autoedici&oacute;n, como&nbsp;</p>\r\n", link: "http://www.youtube.com/watch?v=uHFbIBLTYtE", visit: nil, active: 1, section_id: 1, posted_at: "2014-07-28"},
  {name: "Video de Arte Urbano Grafitti", description: "El punto de usar Lorem Ipsum es que tiene una distribución más o menos normal de las letras", content: "<p>de las letras, al contrario de usar textos como por ejemplo &quot;Contenido aqu&iacute;, contenido aqu&iacute;&quot;. Estos textos hacen parecerlo un espa&ntilde;ol que se puede leer. Muchos paquetes de autoedici&oacute;n y editores de p&aacute;ginas web usan el Lorem Ipsum</p>\r\n", link: "http://www.youtube.com/watch?v=jom8ySBhj44", visit: nil, active: 1, section_id: 1, posted_at: "2013-07-18"},
  {name: "Video de Arte Moderno", description: "contenido del texto de un sitio mientras que mira su diseño. El punto de usar Lorem Ipsum es que tiene ", content: "<p>&nbsp;puede leer. Muchos paquetes de autoedici&oacute;n y editores de p&aacute;ginas web usan el Lorem Ipsum como su texto por defecto, y al hacer una b&uacute;squeda de &quot;Lorem Ipsum&quot; va a dar por resultado muchos sitios web que usan este texto si se encuentran en estado de desarrollo. Muchas versiones han evolucion</p>\r\n", link: "http://www.youtube.com/watch?v=9tZpmHPl2hk", visit: nil, active: 1, section_id: 1, posted_at: "2014-07-24"},
  {name: "VIdeo de Arte Tigre", description: "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en algu", content: "<p>Si vas a utilizar un pasaje de Lorem Ipsum, necesit&aacute;s estar seguro de que no hay nada avergonzante escondido en el medio del texto. Todos los generadores de Lorem Ipsum que se encuentran en Internet tienden a repetir trozos predefinidos cuando sea necesario, haciendo a este el &uacute;nico generador verdadero (v&aacute;li</p>\r\n", link: "http://www.youtube.com/watch?v=PXQrUpB0Jq8", visit: nil, active: 1, section_id: 1, posted_at: "2012-07-27"}
])


